### ISSUE TITLE
Email preferences cannot be saved 

### ISSUE THREAD

**Issue by shane-tomlinson** [mozmeao/basket#358] opened 2019-10-17 05:04 UTC
Refiling from https://github.com/mozilla/fxa/issues/2952

Steps to reproduce:
1.Login to FXA with a valid account
2.From Manage Account page, click the Email Preferences blue link
3.Sign in again when asked
4.On Manage your Email Preferences page, Subscribe to some sections(check the Yes checkboxes from all sections)
5.Click Save Preferences button
6.Perform a Sync and then check again the Email Preferences

Expected results:
Email preferences are correctly saved

Actual results:
Email preferences cannot be saved

Please see a video for this issue :
![FXAPreferences](https://user-images.githubusercontent.com/1583842/66921229-69c19680-f02d-11e9-891a-f8338334d49f.gif)

### Environment

FF69, FF71 with Win10x64.

NOTES:
Issue is reproducible in production

**Comment by pmac** [comment] 2019-10-22 18:50
I still can't, and I have asked others and they also can't. But, none of us are on windows. I'd be very surprised if this was platform-dependent, but we'll be testing on Windows tomorrow to be sure.

**Comment by vcarciu** [comment] 2019-10-31 13:49
I tested again and surprisingly, the issue is not reproducible anymore. I don't know if something changed meanwhile, but now the preferences are correctly saved.

**Comment by pmac** [comment] 2019-11-12 16:14
Closing this for now since we've been unable to find the cause and can no longer reproduce. Please reopen if the problem is seen again.

**Comment by vasilicatamas** [comment] 2019-11-20 12:52
I was able to reproduce this issue again on FxA prod 1.150.4 under Firefox 70.0.1. The subscription changes are not saved after clicking "Save Preferences" button.

![emailpreferences gif](https://user-images.githubusercontent.com/18114210/69239920-04b90d80-0ba4-11ea-8cac-aa304b01d39f.gif)


And the following error is displayed intermittently.

![error](https://user-images.githubusercontent.com/18114210/69239901-f9fe7880-0ba3-11ea-9c38-7674cf029b8d.png)

Could someone please reopen this issue because I don't have permissions on this repository? Thanks!

**Comment by pmac** [comment] 2019-11-20 14:48
Saving preferences is not instantaneous operation. It's an async request. Can you take another look now to see if the prefs have updated? I don't see any errors that would indicate that this failed.

**Comment by pmac** [comment] 2019-11-20 14:49
Or paste the full URL of the preferences page for this user in the issue. I can't get to it myself without the token (the last part of the address).

**Comment by vasilicatamas** [comment] 2019-11-21 14:59
Checked again with the account used in the gif (https://www.mozilla.org/en-US/newsletter/existing/18655b7e-aad7-4158-96dd-41aa8c41b3fb/?fxa=1) and seems that the preferences are saved now. 

@pmac Could you please tell us which is the approximate delay here? This would help to distinguish the server issues more clearly.

**Comment by pmac** [comment] 2019-11-21 16:18
That's tough to say. If everything is running normally and Salesforce isn't having an issue and there is no email going out that drives a lot of newsletter subscriptions, then it can be quite fast. But if there is any issue that might cause the saving of the data to need to be retried or if there is a volume of requests ahead of yours in the queue then it can take anywhere from a few minutes to hours. It shouldn't take that long, but the system is built to make every attempt to save it even if there is a delay for some unforeseen reason.

I'm conflicted on this because it's definitely good to keep an eye on things, but I also don't want to waste your time filing issues that may not be actionable. I'd say maybe give it a few minutes to see if it comes through if it's not immediate before filing.

**Closed** 2020-07-24 15:36 UTC
